## Importing the libraries

In [1]:
import pandas as pd
# Load dataset
df = pd.read_csv(r"C:\Users\umara\Downloads\cleaned_dataset.csv")

In [2]:
df.head()

,InnerBrowRaiseAU1,OuterBrowRaiseAU2,BrowLowererAU4,UpperLidRaiserAU5,CheekRaiserAU6,NoseWrinklerAU9,UpperLipRaiserAU10,LipCornerPullerAU12,DimplerAU14,LipCornerDepressorAU15,...,LipStretcherAU20,LipTightenerAU23,LipPressorAU24,LipsPartAU25,JawDropAU26,MouthStretchAU27,LipSuckAU28,BlinkAU45,HeadTurnLeft,Class
0,0.679261,0.442923,0.882249,0.335754,0.611311,1.0,0.483900,0.824095,1.0,0.273563,...,0.759639,0.208632,1.0,0.377810,0.077131,0.999380,0.619093,0.212896,0.204743,Mild
1,0.634651,0.253620,0.785461,0.287644,0.351515,1.0,0.587167,0.477898,1.0,0.535829,...,0.287342,0.340056,1.0,0.272701,0.154260,0.993663,0.659810,0.164759,0.835940,Mild
2,0.487031,0.211533,0.879955,0.293918,0.446842,1.0,0.581525,0.991549,1.0,0.577000,...,0.652115,0.317500,1.0,0.509740,0.078025,0.996114,0.612727,0.088919,0.713317,Mild
3,0.791155,0.337280,0.788325,0.387807,0.624301,0.0,0.543975,0.381621,0.0,0.337699,...,0.445836,0.258703,1.0,0.340035,0.099870,0.997938,0.598767,0.171855,0.485310,Mild
4,0.686283,0.261061,0.918307,0.318426,0.639545,1.0,0.534016,0.903973,1.0,0.314947,...,0.583217,0.235332,1.0,0.308064,0.062025,0.993485,0.789103,0.205250,0.318147,Mild

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 340989 entries, 0 to 340988
Data columns (total 21 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   InnerBrowRaiseAU1       340989 non-null  float64
 1   OuterBrowRaiseAU2       340989 non-null  float64
 2   BrowLowererAU4          340989 non-null  float64
 3   UpperLidRaiserAU5       340989 non-null  float64
 4   CheekRaiserAU6          340989 non-null  float64
 5   NoseWrinklerAU9         340989 non-null  float64
 6   UpperLipRaiserAU10      340989 non-null  float64
 7   LipCornerPullerAU12     340989 non-null  float64
 8   DimplerAU14             340989 non-null  float64
 9   LipCornerDepressorAU15  340989 non-null  float64
 10  ChinRaiserAU17          340989 non-null  float64
 11  LipStretcherAU20        340989 non-null  float64
 12  LipTightenerAU23        340989 non-null  float64
 13  LipPressorAU24          340989 non-null  float64
 14  LipsPartAU25            340989 non-null  float64
 15  JawDropAU26             340989 non-null  float64
 16  MouthStretchAU27        340989 non-null  float64
 17  LipSuckAU28             340989 non-null  float64
 18  BlinkAU45               340989 non-null  float64
 19  HeadTurnLeft            340989 non-null  float64
 20  Class                   340989 non-null  object
dtypes: float64(20), object(1)
memory usage: 54.6+ MB

In [4]:
df.shape

(340989, 21)

In [ ]:
df.sample(12)

,InnerBrowRaiseAU1,OuterBrowRaiseAU2,BrowLowererAU4,UpperLidRaiserAU5,CheekRaiserAU6,NoseWrinklerAU9,UpperLipRaiserAU10,LipCornerPullerAU12,DimplerAU14,LipCornerDepressorAU15,...,LipStretcherAU20,LipTightenerAU23,LipPressorAU24,LipsPartAU25,JawDropAU26,MouthStretchAU27,LipSuckAU28,BlinkAU45,HeadTurnLeft,Class
76010,0.524123,0.421849,0.463855,0.405581,0.152487,0.0,0.163063,0.016636,0.0,0.086923,...,0.769921,0.611915,0.0,0.672021,0.750709,0.026233,0.224098,0.047014,0.048337,Moderate
287325,0.195254,0.326141,0.444796,0.253169,0.196054,0.0,0.220626,0.022291,1.0,0.044541,...,0.274061,0.488764,0.0,0.550795,0.697043,0.006082,0.108647,0.058369,0.881316,Mild
247183,0.462140,0.265040,0.362251,0.432583,0.228795,0.0,0.180618,0.043058,1.0,0.149115,...,0.594331,0.503933,0.0,0.505803,0.560223,0.492473,0.244241,0.549521,0.113757,Moderate
256429,0.529491,0.390968,0.674424,0.333371,0.716136,1.0,0.721529,0.997226,1.0,0.723958,...,0.183156,0.708666,1.0,0.729320,0.933376,0.060832,0.235803,0.793272,0.393644,Moderate
1098,0.596995,0.365353,0.606765,0.317134,0.887657,1.0,0.467689,0.920519,0.0,0.865502,...,0.518396,0.309804,1.0,0.489692,0.176242,0.915422,0.164155,0.212150,0.641008,Mild
299365,0.805294,0.658798,0.255825,0.685829,0.163076,0.0,0.175161,0.573698,1.0,0.354682,...,0.537106,0.711875,0.0,0.293739,0.457383,0.080458,0.210055,0.074243,0.064877,Mild
128142,0.583725,0.665253,0.108902,0.524934,0.218376,0.0,0.115471,0.036445,1.0,0.135756,...,0.321043,0.546795,0.0,0.537597,0.265863,0.967254,0.030581,0.071778,0.056972,Normal
118583,0.698385,0.481924,0.161489,0.511130,0.358448,1.0,0.112334,0.080591,1.0,0.569301,...,0.363741,0.609442,1.0,0.813254,0.704763,0.123823,0.082944,0.438797,0.022538,Normal
40274,0.743091,0.540115,0.693371,0.476054,0.411820,1.0,0.122926,0.262066,0.0,0.292688,...,0.695866,0.592728,1.0,0.380971,0.345308,0.945132,0.587030,0.306537,0.105664,Moderate
219953,0.731076,0.564917,0.388902,0.548038,0.177500,0.0,0.113784,0.000828,0.0,0.147865,...,0.599342,0.466727,1.0,0.433739,0.469607,0.277630,0.217482,0.118246,0.133673,Moderate
308077,0.534774,0.329222,0.322385,0.422600,0.092515,0.0,0.138866,0.025844,1.0,0.028200,...,0.689318,0.623187,0.0,0.819977,0.653869,0.034182,0.101027,0.805913,0.042518,Mild
267172,0.646432,0.379387,0.371081,0.570813,0.123005,0.0,0.141481,0.013569,0.0,0.114248,...,0.375110,0.537588,1.0,0.681276,0.446778,0.180396,0.401978,0.502947,0.166527,Moderate

In [6]:
df.isnull().sum()

InnerBrowRaiseAU1         0
OuterBrowRaiseAU2         0
BrowLowererAU4            0
UpperLidRaiserAU5         0
CheekRaiserAU6            0
NoseWrinklerAU9           0
UpperLipRaiserAU10        0
LipCornerPullerAU12       0
DimplerAU14               0
LipCornerDepressorAU15    0
ChinRaiserAU17            0
LipStretcherAU20          0
LipTightenerAU23          0
LipPressorAU24            0
LipsPartAU25              0
JawDropAU26               0
MouthStretchAU27          0
LipSuckAU28               0
BlinkAU45                 0
HeadTurnLeft              0
Class                     0
dtype: int64

In [8]:
import seaborn as sns
df = sns.load_dataset("titanic")

In [9]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [3]:
df['Class'].value_counts()

Class
Moderate    145313
Mild        112434
Severe       44442
Normal       38800
Name: count, dtype: int64

In [4]:
# Mapping class labels to numeric values
class_mapping = {"Moderate": 0, "Mild": 1, "Severe": 2, "Normal": 3}
df["Class"] = df["Class"].map(class_mapping)

# Verify the mapping
print(df["Class"].value_counts())  # Check if the values match the original counts

Class
0    145313
1    112434
2     44442
3     38800
Name: count, dtype: int64

In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import pickle


# Define features and target
X = df.drop(columns=["Class"])  # Replace 'target' with your target column
y = df["Class"]
print("Classes are separated")

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and train RandomForestClassifier model
rf_model = RandomForestClassifier()
print("Model is on training...")
rf_model.fit(X_train, y_train)

# Make predictions
y_pred = rf_model.predict(X_test)

# Evaluate model performance
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print("Classification Report:\n", report)

# Save the trained model as a pickle file
with open("random_forest_classifier.pkl", "wb") as file:
    pickle.dump(rf_model, file)

print("Model saved as random_forest_classifier.pkl")

Classes are separated
Model is on training...
Accuracy: 0.8896888471802692
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.95      0.89     28962
           1       0.91      0.79      0.84     22456
           2       0.95      0.89      0.92      8983
           3       0.99      0.95      0.97      7797

    accuracy                           0.89     68198
   macro avg       0.92      0.89      0.91     68198
weighted avg       0.89      0.89      0.89     68198

Model saved as random_forest_classifier.pkl

In [8]:
import pickle

# Load the saved Random Forest model
with open("random_forest_classifier.pkl", "rb") as file:
    loaded_model = pickle.load(file)

# Check the type of the loaded model
print(type(loaded_model))

<class 'sklearn.ensemble._forest.RandomForestClassifier'>